### ISSUE TITLE
MySQL Container constantly restarts

### ISSUE THREAD

**Issue by cerbelding** [123andy/redcap-docker-compose#38] opened 2020-09-21 10:52 UTC
When running `docker-compose up -d` after the configuration of `.env`, the MySQL-Container restarts repeatingly.

The `docker logs` for redcap_db contain a access error for `/var/log/mysql/mysql_error.log`, followed by an Abort-Message.

Docker is Running in version 19.03.12, docker-compose in version 1.26.0 on Ubuntu 20.04.1 LTS

**Comment by bill-mattingly** [comment] 2020-11-13 20:32
I think this is a Duplicate of #11 which has to do with local log folder permissions. The fix described there should work, but I usually fix this by using a docker volume for the mysql logs by changing the .env LOGS_DIR variable to 'logs-volume'
```
LOGS_DIR=logs-volume
# LOGS_DIR=../logs
```

**Comment by 123andy** [comment] 2022-02-16 18:36
Let me know if this is still an issue.  I just did a new release with a lot of changes.

**Closed as completed** 2022-10-06 22:48 UTC
